# Generated by Django 4.0.1 on 2022-01-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orderdate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], max_length=100)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
