# Generated by Django 4.0.1 on 2022-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='orderdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On the way', 'On the way')], default='pending', max_length=100),
        ),
    ]
