# Generated by Django 4.0.1 on 2022-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_placed_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
