# Generated by Django 4.0.1 on 2022-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Return', 'Return'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Packed', 'Packed')], default='pending', max_length=100),
        ),
    ]
