# Generated by Django 4.0.1 on 2022-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Return', 'Return')], default='pending', max_length=100),
        ),
    ]
