# Generated by Django 4.0.1 on 2022-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_placed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed',
            name='sub_total',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('Packed', 'Packed')], default='pending', max_length=100),
        ),
    ]
