# Generated by Django 4.0.1 on 2022-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_products_offer_alter_order_placed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='offer',
        ),
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
    ]
