# Generated by Django 4.0.1 on 2022-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_products_offer_category_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Packed', 'Packed'), ('Return', 'Return'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
