# Generated by Django 4.0.1 on 2022-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_placed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Return', 'Return'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_offer',
            field=models.IntegerField(default=0),
        ),
    ]
