# Generated by Django 4.0.1 on 2022-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_category_category_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_offer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_offer',
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
    ]
