# Generated by Django 4.0.1 on 2022-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_category_category_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Return', 'Return'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
