# Generated by Django 4.0.1 on 2022-02-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_order_placed_status_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='order_placed',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupen_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='pending', max_length=100),
        ),
    ]
