# Generated by Django 4.0.1 on 2022-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_coupon_user_order_placed_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
