# Generated by Django 4.0.1 on 2022-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_order_placed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Return', 'Return')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
