# Generated by Django 4.0.1 on 2022-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_order_placed_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_placed',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Return', 'Return'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
