# Generated by Django 4.0.1 on 2022-02-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_order_placed_coupon_alter_order_placed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coupon'),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('Packed', 'Packed')], default='pending', max_length=100),
        ),
    ]
