# Generated by Django 4.0.1 on 2022-02-08 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_placed_coupon_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
