# Generated by Django 4.0.1 on 2022-02-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_order_placed_status_alter_user_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed',
            name='mode_of_payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('On the way', 'On the way')], default='pending', max_length=100),
        ),
    ]
