# Generated by Django 4.0.1 on 2022-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_order_placed_mode_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Return', 'Return'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
