# Generated by Django 4.0.1 on 2022-02-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_user_details_image_alter_order_placed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='image',
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On the way', 'On the way'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='pending', max_length=100),
        ),
    ]
