# Generated by Django 4.0.1 on 2022-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_user_details_image_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
