# Generated by Django 4.0.1 on 2022-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_order_placed_status_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imageone',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='products',
            name='imagetwo',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
    ]
