# Generated by Django 4.0.1 on 2022-02-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_products_imageone_products_imagetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='guest_user',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='placed', max_length=100),
        ),
    ]
