# Generated by Django 4.0.1 on 2022-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_order_placed_status_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='placed', max_length=100),
        ),
    ]
