# Generated by Django 4.0.1 on 2022-02-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_order_placed_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='placed', max_length=100),
        ),
    ]
