# Generated by Django 4.0.1 on 2022-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_coupon_created_date_alter_order_placed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='placed', max_length=100),
        ),
    ]
